name: Push to Pypi

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-cache-dir -e .[complete]
        pip list
    - name: Build the pypi package
      env:
        func_adl_version: ${{ github.ref }}
      run: |
        python setup_func_adl.py sdist bdist_wheel
        # python setup_func_adl_ast.py sdist bdist_wheel
    - name: Publish a func_adl to PyPI
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
